language: java

branches:
  excludes:
    - gh-pages

notifications:
  email: false
  
env:
  global:
    - ANDROID_SDK_VERSION="r22.0.1"
	- ANDROID_BUILD_TOOLS_VERSION="r17"
    - ANDROID_PLATFORM_TOOLS_VERSION="r17"
    
jdk:
  - openjdk7

before_install:
  # Update a system for ia32 libraries
  # Just full upgrade of system and installing a ia32-libs not works
  # It's debian based system, /very/ stable version only
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # Android
  - export FILE=android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - wget http://dl.google.com/android/${FILE}
  - tar -zxf ${FILE}
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export ANDROID_BUILD_TOOLS_HOME=${ANDROID_HOME}/build-tools/17.0.0
  - export PATH=${ANDROID_BUILD_TOOLS_HOME}:${ANDROID_HOME}/tools:${PATH}
  - rm ${FILE}
  - unset FILE
  
  # Build tools
  # Zip from repository contains android-*.*.* folder inside,
  # we are need only a content from it
  - export BASEDIR=`pwd`
  - mkdir -p ${ANDROID_BUILD_TOOLS_HOME}
  - cd ${ANDROID_BUILD_TOOLS_HOME}
  - export FILE=build-tools_${ANDROID_BUILD_TOOLS_VERSION}-linux.zip
  - wget http://dl.google.com/android/repository/${FILE}
  - unzip -q ${FILE}
  - rm ${FILE}
  - export FILE=$(ls)
  - mv ${FILE}/* .
  - rmdir ${FILE}
  - cd ${BASEDIR}
  - unset FILE
